name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['27', '26', '25']
        rebar3: ['3.24.0']
    runs-on: 'ubuntu-24.04'
    env:
      OTPVER: ${{ matrix.otp }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 fmt --check
      - run: rebar3 lint
      - run: rebar3 do ct --cover
      - run: rebar3 as test codecov analyze
      - run: rebar3 dialyzer
        if: ${{ matrix.otp == '27' }}
      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        if: ${{ matrix.otp == '27' }}
        with:
          files: _build/test/covertool/fast_scram.covertool.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
